# a = [input() for i in range(int(input()))]
# print(a)

words = ['ability', 'able', 'about', 'above', 'accept', 'according', 'account', 'across', 'act', 'action', 'activity',
         'actually', 'add', 'address', 'administration', 'admit', 'adult', 'affect', 'after', 'again', 'against', 'age',
         'agency', 'agent', 'ago', 'agree', 'agreement', 'ahead', 'air', 'all', 'allow', 'almost', 'alone', 'along',
         'already', 'also', 'although', 'always', 'American', 'among', 'amount', 'analysis', 'and', 'animal', 'another',
         'answer', 'any', 'anyone', 'anything', 'appear', 'apply', 'approach', 'area', 'argue', 'arm', 'around',
         'arrive', 'art', 'article', 'artist', 'as', 'ask', 'assume', 'at', 'attack', 'attention', 'attorney',
         'audience', 'author', 'authority', 'available', 'avoid', 'away', 'baby', 'back', 'bad', 'bag', 'ball', 'bank',
         'bar', 'base', 'be', 'beat', 'beautiful', 'because', 'become', 'bed', 'before', 'begin', 'behavior', 'behind',
         'believe', 'benefit', 'best', 'better', 'between', 'beyond', 'big', 'bill', 'billion', 'bit', 'black', 'blood',
         'blue', 'board', 'body', 'book', 'born', 'both', 'box', 'boy', 'break', 'bring', 'brother', 'budget', 'build',
         'building', 'business', 'but', 'buy', 'by', 'call', 'camera', 'campaign', 'can', 'cancer', 'candidate',
         'capital', 'car', 'card', 'care', 'career', 'carry', 'case', 'catch', 'cause', 'cell', 'center', 'central',
         'century', 'certain', 'certainly', 'chair', 'challenge', 'chance', 'change', 'character', 'charge', 'check',
         'child', 'choice', 'choose', 'church', 'citizen', 'city', 'civil', 'claim', 'class', 'clear', 'clearly',
         'close', 'coach', 'cold', 'collection', 'college', 'color', 'come', 'commercial', 'common', 'community',
         'company', 'compare', 'computer', 'concern', 'condition', 'conference', 'Congress', 'consider', 'consumer',
         'contain', 'continue', 'control', 'cost', 'could', 'country', 'couple', 'course', 'court', 'cover', 'create',
         'crime', 'cultural', 'culture', 'cup', 'current', 'customer', 'cut', 'dark', 'data', 'daughter', 'day', 'dead',
         'deal', 'death', 'debate', 'decade', 'decide', 'decision', 'deep', 'defense', 'degree', 'Democrat',
         'democratic', 'describe', 'design', 'despite', 'detail', 'determine', 'develop', 'development', 'die',
         'difference', 'different', 'difficult', 'dinner', 'direction', 'director', 'discover', 'discuss', 'discussion',
         'disease', 'do', 'doctor', 'dog', 'door', 'down', 'draw', 'dream', 'drive', 'drop', 'drug', 'during', 'each',
         'early', 'east', 'easy', 'eat', 'economic', 'economy', 'edge', 'education', 'effect', 'effort', 'eight',
         'either', 'election', 'else', 'employee', 'end', 'energy', 'enjoy', 'enough', 'enter', 'entire', 'environment',
         'environmental', 'especially', 'establish', 'even', 'evening', 'event', 'ever', 'every', 'everybody',
         'everyone', 'everything', 'evidence', 'exactly', 'example', 'executive', 'exist', 'expect', 'experience',
         'expert', 'explain', 'eye', 'face', 'fact', 'factor', 'fail', 'fall', 'family', 'far', 'fast', 'father',
         'fear', 'federal', 'feel', 'feeling', 'few', 'field', 'fight', 'figure', 'fill', 'film', 'final', 'finally',
         'financial', 'find', 'fine', 'finger', 'finish', 'fire', 'firm', 'first', 'fish', 'five', 'floor', 'fly',
         'focus', 'follow', 'food', 'foot', 'for', 'force', 'foreign', 'forget', 'form', 'former', 'forward', 'four',
         'free', 'friend', 'from', 'front', 'full', 'fund', 'future', 'game', 'garden', 'gas', 'general', 'generation',
         'get', 'girl', 'give', 'glass', 'go', 'goal', 'good', 'government', 'great', 'green', 'ground', 'group',
         'grow', 'growth', 'guess', 'gun', 'guy', 'hair', 'half', 'hand', 'hang', 'happen', 'happy', 'hard', 'have',
         'he', 'head', 'health', 'hear', 'heart', 'heat', 'heavy', 'help', 'her', 'here', 'herself', 'high', 'him',
         'himself', 'his', 'history', 'hit', 'hold', 'home', 'hope', 'hospital', 'hot', 'hotel', 'hour', 'house', 'how',
         'however', 'huge', 'human', 'hundred', 'husband', 'I', 'idea', 'identify', 'if', 'image', 'imagine', 'impact',
         'important', 'improve', 'in', 'include', 'including', 'increase', 'indeed', 'indicate', 'individual',
         'industry', 'information', 'inside', 'instead', 'institution', 'interest', 'interesting', 'international',
         'interview', 'into', 'investment', 'involve', 'issue', 'it', 'item', 'its', 'itself', 'job', 'join', 'just',
         'keep', 'key', 'kid', 'kill', 'kind', 'kitchen', 'know', 'knowledge', 'land', 'language', 'large', 'last',
         'late', 'later', 'laugh', 'law', 'lawyer', 'lay', 'lead', 'leader', 'learn', 'least', 'leave', 'left', 'leg',
         'legal', 'less', 'let', 'letter', 'level', 'lie', 'life', 'light', 'like', 'likely', 'line', 'list', 'listen',
         'little', 'live', 'local', 'long', 'look', 'lose', 'loss', 'lot', 'love', 'low', 'machine', 'magazine', 'main',
         'maintain', 'major', 'majority', 'make', 'man', 'manage', 'management', 'manager', 'many', 'market',
         'marriage', 'material', 'matter', 'may', 'maybe', 'me', 'mean', 'measure', 'media', 'medical', 'meet',
         'meeting', 'member', 'memory', 'mention', 'message', 'method', 'middle', 'might', 'military', 'million',
         'mind', 'minute', 'miss', 'mission', 'model', 'modern', 'moment', 'money', 'month', 'more', 'morning', 'most',
         'mother', 'mouth', 'move', 'movement', 'movie', 'Mr', 'Mrs', 'much', 'music', 'must', 'my', 'myself', 'name',
         'nation', 'national', 'natural', 'nature', 'near', 'nearly', 'necessary', 'need', 'network', 'never', 'new',
         'news', 'newspaper', 'next', 'nice', 'night', 'no', 'none', 'nor', 'north', 'not', 'note', 'nothing', 'notice',
         'now', "n't", 'number', 'occur', 'of', 'off', 'offer', 'office', 'officer', 'official', 'often', 'oh', 'oil',
         'ok', 'old', 'on', 'once', 'one', 'only', 'onto', 'open', 'operation', 'opportunity', 'option', 'or', 'order',
         'organization', 'other', 'others', 'our', 'out', 'outside', 'over', 'own', 'owner', 'page', 'pain', 'painting',
         'paper', 'parent', 'part', 'participant', 'particular', 'particularly', 'partner', 'party', 'pass', 'past',
         'patient', 'pattern', 'pay', 'peace', 'people', 'per', 'perform', 'performance', 'perhaps', 'period', 'person',
         'personal', 'phone', 'physical', 'pick', 'picture', 'piece', 'place', 'plan', 'plant', 'play', 'player', 'PM',
         'point', 'police', 'policy', 'political', 'politics', 'poor', 'popular', 'population', 'position', 'positive',
         'possible', 'power', 'practice', 'prepare', 'present', 'president', 'pressure', 'pretty', 'prevent', 'price',
         'private', 'probably', 'problem', 'process', 'produce', 'product', 'production', 'professional', 'professor',
         'program', 'project', 'property', 'protect', 'prove', 'provide', 'public', 'pull', 'purpose', 'push', 'put',
         'quality', 'question', 'quickly', 'quite', 'race', 'radio', 'raise', 'range', 'rate', 'rather', 'reach',
         'read', 'ready', 'real', 'reality', 'realize', 'really', 'reason', 'receive', 'recent', 'recently',
         'recognize', 'record', 'red', 'reduce', 'reflect', 'region', 'relate', 'relationship', 'religious', 'remain',
         'remember', 'remove', 'report', 'represent', 'Republican', 'require', 'research', 'resource', 'respond',
         'response', 'responsibility', 'rest', 'result', 'return', 'reveal', 'rich', 'right', 'rise', 'risk', 'road',
         'rock', 'role', 'room', 'rule', 'run', 'safe', 'same', 'save', 'say', 'scene', 'school', 'science',
         'scientist', 'score', 'sea', 'season', 'seat', 'second', 'section', 'security', 'see', 'seek', 'seem', 'sell',
         'send', 'senior', 'sense', 'series', 'serious', 'serve', 'service', 'set', 'seven', 'several', 'sex', 'sexual',
         'shake', 'share', 'she', 'shoot', 'short', 'shot', 'should', 'shoulder', 'show', 'side', 'sign', 'significant',
         'similar', 'simple', 'simply', 'since', 'sing', 'single', 'sister', 'sit', 'site', 'situation', 'six', 'size',
         'skill', 'skin', 'small', 'smile', 'so', 'social', 'society', 'soldier', 'some', 'somebody', 'someone',
         'something', 'sometimes', 'son', 'song', 'soon', 'sort', 'sound', 'source', 'south', 'southern', 'space',
         'speak', 'special', 'specific', 'speech', 'spend', 'sport', 'spring', 'staff', 'stage', 'stand', 'standard',
         'star', 'start', 'state', 'statement', 'station', 'stay', 'step', 'still', 'stock', 'stop', 'store', 'story',
         'strategy', 'street', 'strong', 'structure', 'student', 'study', 'stuff', 'style', 'subject', 'success',
         'successful', 'such', 'suddenly', 'suffer', 'suggest', 'summer', 'support', 'sure', 'surface', 'system',
         'table', 'take', 'talk', 'task', 'tax', 'teach', 'teacher', 'team', 'technology', 'television', 'tell', 'ten',
         'tend', 'term', 'test', 'than', 'thank', 'that', 'the', 'their', 'them', 'themselves', 'then', 'theory',
         'there', 'these', 'they', 'thing', 'think', 'third', 'this', 'those', 'though', 'thought', 'thousand',
         'threat', 'three', 'through', 'throughout', 'throw', 'thus', 'time', 'to', 'today', 'together', 'tonight',
         'too', 'top', 'total', 'tough', 'toward', 'town', 'trade', 'traditional', 'training', 'travel', 'treat',
         'treatment', 'tree', 'trial', 'trip', 'trouble', 'true', 'truth', 'try', 'turn', 'TV', 'two', 'type', 'under',
         'understand', 'unit', 'until', 'up', 'upon', 'us', 'use', 'usually', 'value', 'various', 'very', 'victim',
         'view', 'violence', 'visit', 'voice', 'vote', 'wait', 'walk', 'wall', 'want', 'war', 'watch', 'water', 'way',
         'we', 'weapon', 'wear', 'week', 'weight', 'well', 'west', 'western', 'what', 'whatever', 'when', 'where',
         'whether', 'which', 'while', 'white', 'who', 'whole', 'whom', 'whose', 'why', 'wide', 'wife', 'will', 'win',
         'wind', 'window', 'wish', 'with', 'within', 'without', 'woman', 'wonder', 'word', 'work', 'worker', 'world',
         'worry', 'would', 'write', 'writer', 'wrong', 'yard', 'yeah', 'year', 'yellow', 'yes', 'yet', 'you', 'young',
         'your',
         'yourself']

two_thousand_words = ['abide', 'ability', 'able', 'about', 'above', 'abroad', 'academic', 'access', 'accommodation',
                      'accomplish', 'account', 'accuracy', 'accurate', 'achieve', 'achievement', 'acknowledge',
                      'acquaintance', 'acquire', 'across', 'act', 'actual', 'actually', 'add', 'additional', 'address',
                      'advance', 'advantage', 'advertise', 'advertisement', 'advice', 'advise', 'advocate', 'affair',
                      'affect', 'afford', 'affordable', 'afraid', 'after', 'afternoon', 'afterwards', 'again',
                      'against', 'age', 'ago', 'agree', 'agreement', 'ahead', 'aid', 'aim', 'albeit', 'alike', 'alive',
                      'all', 'allow', 'allowance', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always',
                      'am', 'amazing', 'amend', 'among', 'amount', 'and', 'anger', 'angry', 'ankle', 'annoy', 'annoyed',
                      'annoying', 'another', 'answer', 'anxious', 'any', 'anymore', 'anyone', 'anything', 'anyway',
                      'apart', 'apologize', 'appeal', 'appear', 'appearance', 'apple', 'application', 'apply',
                      'appointment', 'appraisal', 'appreciate', 'approach', 'appropriate', 'are', 'area', 'argue',
                      'argument', 'arise', 'arm', 'around', 'arrange', 'arrangement', 'array', 'arrive', 'art', 'as',
                      'ashamed', 'aside', 'ask', 'asleep', 'assert', 'assertive', 'assess', 'assessment', 'asset',
                      'assignment', 'assume', 'assumption', 'at', 'Ate', 'attach', 'attached', 'attempt', 'attend',
                      'attention', 'attitude', 'audience', 'aunt', 'available', 'average', 'avoid', 'awake', 'award',
                      'aware', 'awareness', 'away', 'awe', 'awesome', 'awful', 'awkward', 'bachelor', 'back',
                      'background', 'bad', 'bag', 'bake', 'balance', 'bald', 'ball', 'ban', 'band', 'bank', 'bar',
                      'bare', 'barely', 'bargain', 'bark', 'base', 'bass', 'bat', 'batch', 'be', 'beach', 'beam',
                      'bear', 'beard', 'bearing', 'beat', 'beautiful', 'because', 'become', 'bed', 'beef', 'before',
                      'beg', 'begin', 'beginning', 'behave', 'behavior', 'behind', 'being', 'belief', 'believe',
                      'belong', 'below', 'belt', 'bench', 'bend', 'beneath', 'benefit', 'beside', 'besides', 'best',
                      'bet', 'better', 'between', 'beyond', 'bias', 'biased', 'bid', 'big', 'bill', 'bind', 'binding',
                      'bird', 'birthday', 'bit', 'bitch', 'bite', 'bitter', 'blame', 'blanket', 'blast', 'blend',
                      'blind', 'block', 'blood', 'blow', 'blue', 'blunt', 'board', 'boast', 'boat', 'body', 'bold',
                      'bolt', 'bond', 'book', 'boost', 'boot', 'border', 'bore', 'bored', 'boring', 'born', 'borrow',
                      'bossy', 'both', 'bother', 'bottom', 'bounce', 'bound', 'boundary', 'bow', 'bowl', 'box',
                      'branch', 'brand', 'brave', 'breach', 'bread', 'break', 'breakdown', 'breakfast', 'breakthrough',
                      'breath', 'breathe', 'breed', 'bridge', 'brief', 'bright', 'bring', 'broad', 'broadcast', 'broke',
                      'brother', 'brown', 'brush', 'bucket', 'budget', 'bug', 'build', 'building', 'bulk', 'bully',
                      'bump', 'bunch', 'bundle', 'burden', 'burn', 'burst', 'bush', 'business', 'bust', 'busy', 'but',
                      'butt', 'buy', 'buzz', 'by', 'cabbage', 'cake', 'calf', 'call', 'called', 'calm', 'can', 'cap',
                      'car', 'care', 'career', 'careful', 'carefully', 'caring', 'carry', 'case', 'cast', 'cat',
                      'catch', 'cattle', 'caught', 'cause', 'ceiling', 'certain', 'certainly', 'chain', 'chair',
                      'challenge', 'challenging', 'chance', 'chandelier', 'change', 'character', 'charge', 'charity',
                      'charming', 'chart', 'chase', 'cheap', 'cheat', 'check', 'cheek', 'cheeky', 'cheer', 'cheerful',
                      'chest', 'chicken', 'chief', 'child', 'childhood', 'chill', 'chin', 'choice', 'choose', 'chop',
                      'church', 'city', 'claim', 'class', 'clay', 'clean', 'clear', 'clerk', 'clever', 'cliff', 'climb',
                      'close', 'clue', 'clumsy', 'cluster', 'coach', 'coal', 'coat', 'cold', 'colleague', 'collect',
                      'college', 'come', 'comfortable', 'commit', 'commitment', 'committed', 'common', 'commute',
                      'company', 'compelling', 'complain', 'complaint', 'complete', 'compliance', 'comply', 'compound',
                      'comprehensive', 'compulsory', 'computer', 'concern', 'concerned', 'conduct', 'confidence',
                      'confident', 'consider', 'consist', 'consistent', 'constraint', 'contact', 'contain', 'content',
                      'control', 'convenient', 'convey', 'cook', 'cool', 'cope', 'core', 'correct', 'cost', 'costume',
                      'couch', 'cough', 'could', 'count', 'counter', 'country', 'couple', 'course', 'court', 'cousin',
                      'cover', 'crack', 'craft', 'crap', 'crash', 'crawl', 'crazy', 'create', 'creep', 'creepy', 'crew',
                      'crop', 'cross', 'crowd', 'crowded', 'crush', 'cry', 'cuddle', 'cue', 'culture', 'cup',
                      'cupboard', 'curb', 'currency', 'current', 'currently', 'curse', 'custom', 'customer', 'cut',
                      'cute', 'daily', 'damage', 'damn', 'damp', 'dance', 'dangerous', 'dare', 'dark', 'dash', 'data',
                      'date', 'daughter', 'dawn', 'day', 'dead', 'deadline', 'deal', 'dear', 'death', 'deceive',
                      'decide', 'decision', 'deck', 'decline', 'decrease', 'deed', 'deem', 'deep', 'deer', 'default',
                      'defeat', 'definitely', 'degree', 'delay', 'delight', 'delighted', 'deliver', 'delivery',
                      'demand', 'demanding', 'deny', 'depict', 'deploy', 'depth', 'deserve', 'design', 'desire', 'desk',
                      'despite', 'dessert', 'determined', 'develop', 'development', 'device', 'dictionary', 'die',
                      'different', 'difficult', 'dig', 'dim', 'dinner', 'dip', 'dire', 'dirty', 'disappointed',
                      'disclosure', 'discover', 'discuss', 'disease', 'disguise', 'dish', 'dismiss', 'display',
                      'distress', 'ditch', 'dive', 'dizzy', 'do', 'doctor', 'does', 'dog', 'done', 'door', 'doubt',
                      'down', 'draft', 'drag', 'drain', 'draw', 'drawback', 'drawer', 'drawing', 'drawn', 'dread',
                      'dreadful', 'dream', 'dress', 'drift', 'drill', 'drink', 'drive', 'drop', 'drought', 'drown',
                      'dry', 'due', 'dull', 'dumb', 'dump', 'during', 'dust', 'duty', 'dwell', 'dying', 'each', 'eager',
                      'ear', 'early', 'earn', 'ease', 'easy', 'eat', 'edge', 'effect', 'effective', 'effort', 'either',
                      'elbow', 'elderly', 'else', 'embarrassed', 'embed', 'embedded', 'embrace', 'emphasize',
                      'employee', 'employer', 'empty', 'enable', 'encompass', 'encounter', 'encourage', 'end',
                      'endeavor', 'endorse', 'endorsement', 'endure', 'engage', 'engaged', 'engagement', 'engine',
                      'English', 'enhance', 'enjoy', 'enough', 'ensure', 'entail', 'enter', 'entire', 'environment',
                      'equipment', 'equity', 'escape', 'especially', 'essay', 'establish', 'even', 'evening', 'event',
                      'eventually', 'ever', 'every', 'everyone', 'everything', 'everywhere', 'evidence', 'evil',
                      'example', 'except', 'exchange', 'excited', 'exciting', 'exercise', 'expect', 'expensive',
                      'experience', 'expertise', 'explain', 'extent', 'face', 'facility', 'fact', 'fade', 'fail',
                      'failure', 'faint', 'fair', 'fairly', 'faith', 'fake', 'Fall', 'family', 'famous', 'fan', 'fancy',
                      'far', 'fare', 'farewell', 'farm', 'fashion', 'fast', 'fat', 'fate', 'fault', 'favorite', 'fear',
                      'feasible', 'feature', 'fee', 'feed', 'feedback', 'feel', 'feeling', 'fell', 'fellow', 'felt',
                      'fence', 'fetch', 'few', 'field', 'fierce', 'fight', 'figure', 'file', 'fill', 'filthy',
                      'finally', 'find', 'fine', 'finish', 'fire', 'firm', 'first', 'fish', 'fit', 'fix', 'flat',
                      'flaw', 'flawless', 'flee', 'flight', 'flip', 'flood', 'floor', 'flow', 'flu', 'fly', 'focus',
                      'fold', 'follow', 'following', 'fond', 'food', 'fool', 'foolish', 'foot', 'for', 'force',
                      'forecast', 'foreign', 'forget', 'forgive', 'form', 'former', 'forth', 'forward', 'foster',
                      'found', 'frame', 'framework', 'freak', 'free', 'freight', 'French', 'friend', 'friendly',
                      'frightened', 'fringe', 'from', 'front', 'frown', 'fuck', 'fuel', 'fulfill', 'full', 'fun',
                      'fund', 'funny', 'fur', 'furniture', 'further', 'furthermore', 'fuss', 'gain', 'game', 'gap',
                      'gate', 'gather', 'gathering', 'gauge', 'gaze', 'gear', 'gender', 'gentle', 'get', 'gift', 'give',
                      'glad', 'glance', 'glass', 'glimpse', 'gloomy', 'glow', 'go', 'goal', 'goat', 'going', 'good',
                      'gorgeous', 'gossip', 'government', 'grab', 'grade', 'graduate', 'grant', 'granted', 'grasp',
                      'grass', 'grateful', 'grave', 'great', 'greed', 'greedy', 'greet', 'grid', 'grief', 'grim',
                      'grin', 'grind', 'grip', 'groom', 'gross', 'ground', 'grow', 'growth', 'guess', 'guest', 'guilty',
                      'gut', 'hail', 'hair', 'half', 'hall', 'Halloween', 'hand', 'handle', 'handsome', 'hang',
                      'happen', 'happiness', 'happy', 'hard', 'hardly', 'harm', 'harmful', 'harness', 'harsh',
                      'harvest', 'has', 'hat', 'hate', 'hatred', 'have', 'hazard', 'he', 'head', 'heal', 'health',
                      'healthy', 'hear', 'heard', 'heart', 'heat', 'heavy', 'hedge', 'heel', 'height', 'held', 'hell',
                      'hello', 'help', 'helpful', 'hence', 'her', 'here', 'heritage', 'hesitate', 'hi', 'hidden',
                      'hide', 'high', 'highlight', 'hike', 'hiking', 'hill', 'him', 'hinder', 'hint', 'hip', 'hire',
                      'his', 'history', 'hit', 'hoax', 'hold', 'hole', 'holiday', 'hollow', 'home', 'homework', 'hood',
                      'hook', 'hope', 'hopefully', 'host', 'hot', 'house', 'household', 'how', 'however', 'hub', 'hug',
                      'huge', 'humble', 'hungry', 'hunt', 'hurry', 'hurt', 'husband', 'I', 'idea', 'idle', 'if', 'ill',
                      'illness', 'impact', 'implement', 'imply', 'important', 'impressive', 'improve', 'improvement',
                      'in', 'include', 'including', 'income', 'increase', 'indeed', 'influence', 'information',
                      'injury', 'inner', 'input', 'inquiry', 'inside', 'insight', 'instance', 'instead', 'insurance',
                      'intend', 'interest', 'interested', 'interesting', 'interview', 'into', 'introduce', 'invoice',
                      'involve', 'involved', 'iron', 'is', 'issue', 'IT', 'item', 'its', 'jacket', 'jam', 'jar',
                      'jealous', 'jerk', 'job', 'join', 'joint', 'joke', 'journey', 'judge', 'jump', 'junk', 'just',
                      'keen', 'keep', 'key', 'kick', 'kill', 'kind', 'knee', 'knock', 'know', 'knowledge', 'label',
                      'lack', 'ladder', 'lame', 'land', 'landmark', 'landscape', 'language', 'lap', 'large', 'last',
                      'late', 'later', 'latter', 'laugh', 'launch', 'law', 'lawn', 'lawyer', 'lay', 'layer', 'layout',
                      'lazy', 'lead', 'leader', 'leading', 'leaf', 'leak', 'lean', 'leap', 'learn', 'lease', 'least',
                      'leather', 'leave', 'lecture', 'LED', 'left', 'leg', 'legacy', 'leisure', 'lend', 'length',
                      'less', 'let', 'letter', 'level', 'leverage', 'liability', 'lie', 'life', 'lift', 'light', 'like',
                      'likelihood', 'likely', 'likewise', 'limb', 'line', 'linger', 'link', 'listen', 'litter',
                      'little', 'live', 'lively', 'load', 'loan', 'location', 'lock', 'log', 'lonely', 'long', 'look',
                      'loop', 'loose', 'lose', 'loss', 'lost', 'lot', 'loud', 'love', 'lovely', 'low', 'lower', 'loyal',
                      'lucky', 'luggage', 'lump', 'lunch', 'lying', 'mad', 'made', 'main', 'mainly', 'mainstream',
                      'maintain', 'major', 'make', 'mall', 'man', 'manage', 'management', 'manager', 'manner', 'many',
                      'mark', 'market', 'married', 'master', 'match', 'mate', 'matter', 'May', 'maybe', 'ME', 'meal',
                      'mean', 'meaning', 'means', 'meanwhile', 'measure', 'meat', 'media', 'meet', 'meeting', 'melt',
                      'merely', 'merge', 'mess', 'messy', 'middle', 'might', 'mild', 'mind', 'mine', 'miss', 'mistake',
                      'mock', 'money', 'month', 'mood', 'moody', 'more', 'moreover', 'morning', 'mortgage', 'most',
                      'mostly', 'mother', 'mouth', 'move', 'much', 'mud', 'murder', 'music', 'must', 'my', 'nail',
                      'naive', 'name', 'nap', 'narrow', 'nasty', 'nature', 'naughty', 'near', 'nearby', 'nearly',
                      'neat', 'necessary', 'neck', 'need', 'neglect', 'neighborhood', 'neither', 'nephew', 'net',
                      'network', 'never', 'nevertheless', 'new', 'news', 'next', 'nice', 'niece', 'night', 'nod',
                      'noise', 'noisy', 'none', 'nonetheless', 'not', 'note', 'nothing', 'notice', 'now', 'nowadays',
                      'null', 'numb', 'nurse', 'nurture', 'nut', 'obviously', 'occur', 'odd', 'odds', 'of', 'off',
                      'offer', 'offset', 'often', 'old', 'on', 'once', 'one', 'ongoing', 'only', 'onto', 'open',
                      'opportunity', 'opposite', 'or', 'order', 'other', 'otherwise', 'ought', 'our', 'out', 'outbreak',
                      'outcome', 'outfit', 'outgoing', 'outline', 'outlook', 'output', 'outside', 'outskirts',
                      'outstanding', 'oven', 'over', 'overall', 'overcome', 'overlap', 'overlook', 'overview',
                      'overwhelmed', 'overwhelming', 'owe', 'own', 'owner', 'pace', 'pack', 'pain', 'paint', 'painting',
                      'pale', 'Pan', 'paper', 'park', 'part', 'partner', 'party', 'pass', 'past', 'path', 'patient',
                      'pattern', 'pay', 'peak', 'peer', 'pen', 'people', 'perform', 'performance', 'perhaps', 'period',
                      'perk', 'person', 'pick', 'picture', 'pie', 'piece', 'pin', 'pit', 'pitch', 'pity', 'place',
                      'plain', 'plan', 'plant', 'plate', 'play', 'pleasant', 'please', 'pleased', 'pleasure', 'pledge',
                      'plenty', 'plot', 'plug', 'point', 'policy', 'polite', 'pond', 'pool', 'poor', 'popular',
                      'position', 'post', 'pot', 'pound', 'pour', 'power', 'powerful', 'practice', 'praise', 'prefer',
                      'present', 'press', 'pressure', 'pretend', 'pretty', 'prevent', 'previous', 'pride', 'principal',
                      'prior', 'problem', 'proceed', 'process', 'profit', 'promise', 'promote', 'prompt', 'prone',
                      'proof', 'proper', 'properly', 'property', 'proposal', 'prospect', 'proud', 'prove', 'provide',
                      'provided', 'provision', 'pull', 'pumpkin', 'purchase', 'purpose', 'purse', 'pursue', 'pursuit',
                      'push', 'put', 'question', 'queue', 'quick', 'quickly', 'quiet', 'quit', 'quite', 'quote', 'race',
                      'rack', 'rain', 'raise', 'raised', 'random', 'range', 'rank', 'rare', 'rash', 'rate', 'rather',
                      'raw', 'reach', 'read', 'ready', 'real', 'realize', 'really', 'rear', 'reason', 'recall',
                      'receipt', 'receive', 'recently', 'reckless', 'reckon', 'recognize', 'recommend', 'record',
                      'recover', 'refer', 'reference', 'reflect', 'refund', 'refuse', 'regard', 'regarding',
                      'regardless', 'regret', 'relate', 'related', 'relationship', 'relative', 'relax', 'release',
                      'relevant', 'reliability', 'reliable', 'relief', 'relieve', 'reluctant', 'rely', 'remain',
                      'remember', 'remind', 'remove', 'render', 'rent', 'reply', 'report', 'request', 'require',
                      'required', 'requirement', 'research', 'resemble', 'resort', 'resource', 'respect', 'response',
                      'responsible', 'rest', 'result', 'resume', 'retail', 'retain', 'retrieve', 'return', 'reveal',
                      'revenue', 'review', 'reward', 'rich', 'rid', 'ride', 'right', 'ring', 'rise', 'risk', 'road',
                      'rock', 'role', 'roll', 'roof', 'room', 'root', 'rope', 'rough', 'roughly', 'round', 'row', 'rub',
                      'rubber', 'rubbish', 'rude', 'rug', 'rule', 'run', 'running', 'rush', 'sad', 'safe', 'safety',
                      'said', 'sail', 'sake', 'same', 'sample', 'sand', 'SAT', 'save', 'saw', 'say', 'scale', 'scared',
                      'scarf', 'scary', 'schedule', 'scheme', 'school', 'scope', 'score', 'scrap', 'scratch', 'scream',
                      'screen', 'screw', 'seal', 'search', 'season', 'seat', 'see', 'seed', 'seek', 'seem', 'seize',
                      'seldom', 'selfish', 'sell', 'send', 'sense', 'sensible', 'sensitive', 'sentence', 'serious',
                      'serve', 'service', 'set', 'setting', 'settle', 'settlement', 'several', 'shade', 'shake',
                      'shall', 'shallow', 'shame', 'shape', 'share', 'sharp', 'shed', 'sheep', 'sheer', 'sheet',
                      'shelf', 'shell', 'shelter', 'shield', 'shift', 'shine', 'ship', 'shirt', 'shit', 'shoot', 'shop',
                      'shopping', 'shore', 'short', 'shortage', 'shot', 'should', 'shoulder', 'shout', 'show', 'shower',
                      'shrink', 'shut', 'shy', 'sibling', 'sick', 'side', 'sigh', 'sight', 'sightseeing', 'sign',
                      'significant', 'silly', 'similar', 'sin', 'since', 'sincerely', 'sing', 'single', 'sink',
                      'sister', 'sit', 'size', 'skill', 'skin', 'skinny', 'skip', 'skirt', 'slang', 'sleep', 'sleeve',
                      'slice', 'slide', 'slight', 'slightly', 'slim', 'slip', 'slope', 'slow', 'small', 'smart',
                      'smell', 'smile', 'smooth', 'snap', 'snow', 'so', 'soak', 'soar', 'soft', 'soil', 'sole', 'solve',
                      'some', 'somehow', 'someone', 'something', 'son', 'soon', 'sore', 'sorrow', 'sorry', 'sort',
                      'sought', 'soul', 'sound', 'sour', 'source', 'span', 'spare', 'spark', 'speak', 'speech', 'spell',
                      'spend', 'spill', 'spin', 'split', 'spoil', 'spooky', 'spot', 'spread', 'spring', 'square',
                      'squeeze', 'stack', 'staff', 'stage', 'stain', 'stake', 'stakeholder', 'stall', 'stand',
                      'standard', 'stare', 'start', 'state', 'statement', 'status', 'stay', 'steady', 'steak', 'steal',
                      'steam', 'steel', 'steep', 'steer', 'stem', 'step', 'stick', 'stiff', 'still', 'sting', 'stir',
                      'stock', 'stop', 'storage', 'store', 'storm', 'story', 'stove', 'straight', 'straightforward',
                      'strain', 'strange', 'straw', 'stream', 'strength', 'strengthen', 'stress', 'stretch', 'strict',
                      'strike', 'striking', 'string', 'strip', 'strive', 'stroke', 'stroll', 'strong', 'struck',
                      'struggle', 'stubborn', 'stuck', 'student', 'study', 'stuff', 'stumble', 'stunning', 'subject',
                      'submit', 'subtle', 'succeed', 'success', 'successful', 'such', 'suck', 'suddenly', 'suffer',
                      'suggest', 'suit', 'suitable', 'summary', 'summer', 'sunset', 'supply', 'support', 'sure',
                      'surface', 'surge', 'surgery', 'surname', 'surrender', 'surround', 'surrounding', 'survey',
                      'swallow', 'swap', 'sway', 'swear', 'sweat', 'sweater', 'sweep', 'sweet', 'swell', 'swim',
                      'swing', 'switch', 'swollen', 'sympathetic', 'table', 'tackle', 'tail', 'take', 'talk',
                      'talkative', 'tall', 'tap', 'target', 'task', 'taste', 'taught', 'teach', 'teacher', 'team',
                      'tear', 'tease', 'tell', 'tend', 'tender', 'tense', 'term', 'test', 'than', 'that', 'the',
                      'their', 'them', 'themselves', 'then', 'there', 'thereby', 'therefore', 'these', 'they', 'thick',
                      'thief', 'thigh', 'thin', 'thing', 'think', 'this', 'thorough', 'thoroughly', 'those', 'though',
                      'thought', 'thoughtful', 'thread', 'threat', 'threaten', 'threshold', 'thrill', 'thrive',
                      'throat', 'through', 'throughout', 'throw', 'thrust', 'thumb', 'Thursday', 'thus', 'tick', 'tide',
                      'tidy', 'tie', 'tight', 'till', 'time', 'tin', 'tiny', 'tip', 'tired', 'to', 'today', 'toe',
                      'together', 'toll', 'tomorrow', 'tongue', 'too', 'tool', 'top', 'topic', 'torn', 'toss', 'touch',
                      'tough', 'toward', 'town', 'trace', 'track', 'trade', 'trail', 'train', 'training', 'trait',
                      'transcription', 'trap', 'travel', 'treat', 'treatment', 'tree', 'trend', 'trial', 'trick',
                      'tricky', 'trigger', 'trim', 'trip', 'trouble', 'trough', 'true', 'truly', 'trunk', 'trust',
                      'trustworthy', 'truth', 'try', 'Tuesday', 'turkey', 'turn', 'turnover', 'twist', 'type', 'ugly',
                      'uncle', 'undefined', 'under', 'undergo', 'underlying', 'undermine', 'underneath', 'understand',
                      'understanding', 'undertake', 'unfortunately', 'unique', 'unless', 'unlike', 'unlikely', 'until',
                      'up', 'update', 'upgrade', 'upon', 'upset', 'urge', 'us', 'use', 'used', 'useful', 'usually',
                      'utterly', 'vacuum', 'valuable', 'value', 'venture', 'venue', 'very', 'vessel', 'view', 'visit',
                      'void', 'vtr', 'wage', 'waist', 'wait', 'wake', 'walk', 'wall', 'wallet', 'wander', 'want',
                      'ward', 'warehouse', 'warm', 'warn', 'warning', 'wash', 'waste', 'watch', 'water', 'wave', 'way',
                      'we', 'weak', 'weakness', 'wealth', 'wealthy', 'wear', 'weather', 'Wednesday', 'week', 'weekend',
                      'weight', 'weird', 'welcome', 'welfare', 'well', 'went', 'were', 'wet', 'what', 'whatever',
                      'wheat', 'wheel', 'when', 'whenever', 'where', 'whereas', 'whether', 'which', 'while', 'whilst',
                      'whip', 'WHO', 'whole', 'whom', 'whose', 'why', 'wicked', 'wide', 'widely', 'widespread', 'width',
                      'wife', 'wiggle', 'wild', 'will', 'willing', 'willingness', 'win', 'wind', 'window', 'wipe',
                      'wire', 'wisdom', 'wise', 'wish', 'wit', 'witch', 'with', 'withdraw', 'withdrawal', 'within',
                      'without', 'witness', 'witty', 'woman', 'wonder', 'wonderful', 'wood', 'word', 'work', 'world',
                      'worn', 'worried', 'worry', 'worse', 'worship', 'worst', 'worth', 'worthwhile', 'worthy', 'would',
                      'wound', 'wrap', 'wreck', 'wrist', 'write', 'writing', 'wrong', 'yard', 'year', 'yell', 'yet',
                      'yield', 'you', 'young', 'your', 'youth']

high_tech = ['algorithm', 'artificial intelligence', 'automation', 'big data', 'blockchain', 'cloud computing',
             'coding', 'cryptocurrency', 'cybersecurity', 'data analytics', 'digitalization', 'encryption', 'firewall',
             'genetic engineering', 'internet of Things (IoT)', 'machine learning', 'nanotechnology', 'network',
             'robotics', 'virtual reality', 'augmented reality', 'biometrics', 'chatbot', 'data mining', 'E-commerce',
             'holography', 'internet', 'mobile app', 'quantum computing', 'sensor', 'software', '3D printing',
             'biotechnology', 'crowdfunding', 'data center', 'drone', 'GPS', 'innovation', 'mobile device',
             'renewable energy', 'satellite', 'social media', 'startup', 'Wi-Fi', 'analytics',
             'artificial neural network', 'cyberattack', 'digital marketing', 'facial recognition', 'internet browser',
             'machine vision', 'nanomaterials', 'programming', 'quantum mechanics', 'semiconductor', 'smart home',
             'telecommunication', 'virtual assistant', 'wearable technology', 'automation', 'big data analytics',
             'cloud storage', 'data privacy', 'internet security', 'machine translation', 'network security',
             'quantum encryption', 'social networking', 'user interface', 'artificial general intelligence',
             'cybercrime', 'data visualization', 'E-waste', 'internet service provider', 'malware',
             'network infrastructure', 'quantum superposition', 'software development', 'cyber warfare',
             'deep learning', 'internet of Everything (IoE)', 'nanomedicine', 'optical fiber', 'quantum teleportation',
             'robotics process automation', 'software engineering', 'user experience (UX)', 'artificial consciousness',
             'cybernetics', 'data breach', 'edge computing', 'internet censorship', 'machine vision',
             'natural language processing', 'quantum entanglement', 'robotic process automation',
             'virtual private network (VPN)', 'artificial life', 'cyberbullying', 'data compression']
